queue_rules:
  - name: production
    queue_conditions:
      - base = main
    merge_conditions: []
    merge_method: merge
  - name: sandbox
    queue_conditions:
      - base = rel
    merge_conditions:
      - check-success = sandbox-only-gate
    merge_method: merge

pull_request_rules: []
