queue_rules:
  - name: production
    queue_conditions:
      - base = main
    merge_conditions:
      - check-success = full-e2e
    merge_method: merge
  - name: sandbox
    queue_conditions:
      - base = rel
    merge_conditions: []
    merge_method: merge

pull_request_rules:
  - name: auto-queue sandbox work only
    conditions:
      - base = rel
    actions:
      queue:
